In [123]:
import numpy as np

In [124]:
a = np.array([[1,2,3], 
             [4,5,6]])

In [125]:
a.shape

(2, 3)

In [126]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [127]:
a[0]

1

In [128]:
a[0]=10
a

array([10,  2,  3,  4,  5,  6,  7,  8])

In [129]:
a[0:3]

array([10,  2,  3])

In [130]:
a[:4]

array([10,  2,  3,  4])

In [131]:
a[5:]

array([6, 7, 8])

In [132]:
a = np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])
a

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
a[1,2]

6

In [134]:
a[1:, 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [135]:
a.ndim

2

In [136]:
a.shape

(3, 4)

In [137]:
len(a.shape) == a.ndim

True

In [138]:
a.size

12

In [139]:
a.dtype

dtype('int32')

In [140]:
np.zeros(4)

array([0., 0., 0., 0.])

In [141]:
np.zeros((2,3), np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [142]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [143]:
np.ones((4,4,5), np.float16)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float16)

In [144]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [145]:
np.arange(4)

array([0, 1, 2, 3])

In [146]:
np.arange(2,100)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [147]:
np.arange(2,100,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50,
       53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [148]:
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [149]:
array = np.array([45,12,234,67,89,90,123,54])
np.sort(array)

array([ 12,  45,  54,  67,  89,  90, 123, 234])

In [150]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [151]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [152]:
array_example.shape

(3, 2, 4)

In [153]:
array_example.ndim

3

In [154]:
array_example.size

24

In [155]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [156]:
b = a.reshape((2,3))
b

array([[0, 1, 2],
       [3, 4, 5]])

In [157]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [158]:
a = a[np.newaxis,:]
a.shape

(1, 6)

In [159]:
vector = np.array([2,4,6,8,10])
vector.shape

(5,)

In [160]:
row_vector = vector[np.newaxis,:]
row_vector.shape

(1, 5)

In [161]:
column_vector = vector[:, np.newaxis]
column_vector.shape

(5, 1)

In [162]:
vector = np.array([1,3,5,7,9])
vector.shape

(5,)

In [163]:
row_vector = np.expand_dims(vector, axis = 0)
row_vector.shape

(1, 5)

In [164]:
column_vector = np.expand_dims(vector, axis = 1)
column_vector.shape

(5, 1)

In [165]:
data = np.array([1,2,3,4])
data

array([1, 2, 3, 4])

In [166]:
data[0]

1

In [167]:
data[0:3]

array([1, 2, 3])

In [168]:
data[:3]

array([1, 2, 3])

In [169]:
data[2:4]

array([3, 4])

In [170]:
data[3:]

array([4])

In [171]:
a = np.array([[1,2,3,4], [4,5,6,7], [8,9,10,11]])
a

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [172]:
a[a>5].reshape((2,3))

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [173]:
five_up = (a >= 5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11])

In [174]:
a[a % 2 == 0]

array([ 2,  4,  4,  6,  8, 10])

In [175]:
a[(a > 2) & (a < 8)]

array([3, 4, 4, 5, 6, 7])

In [176]:
array1 = np.array([[1,2], [3,4]])
array2 = np.array([[5,6], [7,8]])
array1, array2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [177]:
vertical_stack = np.vstack((array1, array2))
vertical_stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [178]:
horizontal_stack = np.hstack((array1, array2))
horizontal_stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [179]:
large_array = np.arange(1, 25).reshape(2, 12)
large_array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [180]:
np.hsplit(large_array, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [181]:
np.hsplit(large_array, 4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

In [182]:
array = np.array([2,3])
array

array([2, 3])

In [183]:
ones_array = np.ones(2, dtype=np.int8)
ones_array

array([1, 1], dtype=int8)

In [184]:
matrix_addition = array + ones_array
matrix_addition

array([3, 4])

In [185]:
matrix_subtraction = array - ones_array
matrix_subtraction

array([1, 2])

In [186]:
matrix_multiplication = array * ones_array
matrix_multiplication

array([2, 3])

In [187]:
matrix_division = array / ones_array
matrix_division

array([2., 3.])

In [188]:
a = np.array([1,2,3,4])
a.sum()

10

In [189]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [190]:
rowwise_sum = b.sum(axis = 0)
rowwise_sum

array([15, 18, 21, 24])

In [191]:
columnwise_sum = b.sum(axis = 1)
columnwise_sum

array([10, 26, 42])

In [192]:
broadcasting_array = np.array([1, 2, 4], dtype = np.float16)
broadcasting_array

array([1., 2., 4.], dtype=float16)

In [193]:
broadcasting_value = broadcasting_array * 1.45
broadcasting_value

array([1.45, 2.9 , 5.8 ], dtype=float16)

In [194]:
broadcasting_value.max()

5.8

In [195]:
broadcasting_value.min()

1.45

In [196]:
broadcasting_value.sum()

10.15

In [197]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [198]:
a.sum()

4.8595784

In [199]:
a.sum(axis=0)

array([1.12378257, 1.04875507, 1.01034462, 1.67669614])

In [200]:
a.sum(axis=1)

array([1.51832856, 1.55434556, 1.78690428])

In [201]:
a.max()

0.82485143

In [202]:
a.max(axis=0)

array([0.54627315, 0.82485143, 0.40067661, 0.56917101])

In [203]:
a.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [204]:
a.min()

0.05093587

In [205]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [206]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [207]:
data = np.array([[1,2], [3,4], [5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [208]:
data[:,:]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [209]:
data[1:,:]

array([[3, 4],
       [5, 6]])

In [210]:
data[1:,:].max()

6

In [211]:
data[1:,:].min()

3

In [212]:
data[1:,:].sum()

18

In [213]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [214]:
ones_row = np.array([[1, 1]])
ones_row

array([[1, 1]])

In [215]:
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [216]:
np.ones(3)

array([1., 1., 1.])

In [217]:
np.zeros(3)

array([0., 0., 0.])

In [218]:
rng = np.random.default_rng()
rng.random(3)

array([0.96570133, 0.14058466, 0.93238039])

In [219]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [220]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [221]:
rng.random((2,3))

array([[0.32536444, 0.46659417, 0.50526518],
       [0.12890935, 0.11405655, 0.73387401]])

In [222]:
rng.integers(5, size=(4,4))

array([[3, 0, 2, 2],
       [1, 2, 3, 1],
       [0, 3, 1, 2],
       [2, 2, 4, 2]], dtype=int64)

In [223]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
a

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [224]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [225]:
np.unique(a, return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64))

In [226]:
np.unique(a, return_counts=True) 

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1], dtype=int64))

In [227]:
np.unique(a, return_inverse=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([0, 0, 1, 2, 3, 4, 5, 6, 1, 2, 0, 3, 7, 8, 9], dtype=int64))

In [228]:
twoDimensionalMatrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
twoDimensionalMatrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [229]:
np.unique(twoDimensionalMatrix, axis = 0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [230]:
np.unique(twoDimensionalMatrix, axis = 1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [231]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [232]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [233]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [234]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [235]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [236]:
np.flip(a)

array([20, 19, 18, 14, 11, 13, 12, 17, 16, 15, 14, 13, 12, 11, 11])

In [237]:
matrix2Dimensional = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix2Dimensional

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [238]:
np.flip(matrix2Dimensional)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [239]:
reveresed_column = np.flip(matrix2Dimensional, axis=0)
reveresed_column

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [240]:
reversed_rows = np.flip(matrix2Dimensional, axis=1)
reversed_rows

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [241]:
matrix = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [242]:
matrix.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [243]:
matrix.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])