In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3], 
             [4,5,6]])

In [3]:
a.shape

(2, 3)

In [4]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
a[0]

1

In [6]:
a[0]=10
a

array([10,  2,  3,  4,  5,  6,  7,  8])

In [7]:
a[0:3]

array([10,  2,  3])

In [8]:
a[:4]

array([10,  2,  3,  4])

In [9]:
a[5:]

array([6, 7, 8])

In [10]:
a = np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])
a

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
a[1,2]

6

In [12]:
a[1:, 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [13]:
a.ndim

2

In [14]:
a.shape

(3, 4)

In [15]:
len(a.shape) == a.ndim

True

In [16]:
a.size

12

In [17]:
a.dtype

dtype('int32')

In [18]:
np.zeros(4)

array([0., 0., 0., 0.])

In [19]:
np.zeros((2,3), np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((4,4,5), np.float16)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float16)

In [22]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [23]:
np.arange(4)

array([0, 1, 2, 3])

In [24]:
np.arange(2,100)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [25]:
np.arange(2,100,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50,
       53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [26]:
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [27]:
array = np.array([45,12,234,67,89,90,123,54])
np.sort(array)

array([ 12,  45,  54,  67,  89,  90, 123, 234])

In [28]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [30]:
array_example.shape

(3, 2, 4)

In [31]:
array_example.ndim

3

In [32]:
array_example.size

24

In [33]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [34]:
b = a.reshape((2,3))
b

array([[0, 1, 2],
       [3, 4, 5]])

In [35]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [36]:
a = a[np.newaxis,:]
a.shape

(1, 6)

In [37]:
vector = np.array([2,4,6,8,10])
vector.shape

(5,)

In [38]:
row_vector = vector[np.newaxis,:]
row_vector.shape

(1, 5)

In [39]:
column_vector = vector[:, np.newaxis]
column_vector.shape

(5, 1)

In [40]:
vector = np.array([1,3,5,7,9])
vector.shape

(5,)

In [41]:
row_vector = np.expand_dims(vector, axis = 0)
row_vector.shape

(1, 5)

In [42]:
column_vector = np.expand_dims(vector, axis = 1)
column_vector.shape

(5, 1)

In [43]:
data = np.array([1,2,3,4])
data

array([1, 2, 3, 4])

In [44]:
data[0]

1

In [45]:
data[0:3]

array([1, 2, 3])

In [46]:
data[:3]

array([1, 2, 3])

In [47]:
data[2:4]

array([3, 4])

In [48]:
data[3:]

array([4])

In [49]:
a = np.array([[1,2,3,4], [4,5,6,7], [8,9,10,11]])
a

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
a[a>5].reshape((2,3))

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
five_up = (a >= 5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11])

In [52]:
a[a % 2 == 0]

array([ 2,  4,  4,  6,  8, 10])

In [53]:
a[(a > 2) & (a < 8)]

array([3, 4, 4, 5, 6, 7])

In [54]:
array1 = np.array([[1,2], [3,4]])
array2 = np.array([[5,6], [7,8]])
array1, array2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [55]:
vertical_stack = np.vstack((array1, array2))
vertical_stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [56]:
horizontal_stack = np.hstack((array1, array2))
horizontal_stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [57]:
large_array = np.arange(1, 25).reshape(2, 12)
large_array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [58]:
np.hsplit(large_array, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [59]:
np.hsplit(large_array, 4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

In [60]:
array = np.array([2,3])
array

array([2, 3])

In [61]:
ones_array = np.ones(2, dtype=np.int8)
ones_array

array([1, 1], dtype=int8)

In [62]:
matrix_addition = array + ones_array
matrix_addition

array([3, 4])

In [63]:
matrix_subtraction = array - ones_array
matrix_subtraction

array([1, 2])

In [64]:
matrix_multiplication = array * ones_array
matrix_multiplication

array([2, 3])

In [65]:
matrix_division = array / ones_array
matrix_division

array([2., 3.])

In [66]:
a = np.array([1,2,3,4])
a.sum()

10

In [67]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
rowwise_sum = b.sum(axis = 0)
rowwise_sum

array([15, 18, 21, 24])

In [69]:
columnwise_sum = b.sum(axis = 1)
columnwise_sum

array([10, 26, 42])

In [70]:
broadcasting_array = np.array([1, 2, 4], dtype = np.float16)
broadcasting_array

array([1., 2., 4.], dtype=float16)

In [71]:
broadcasting_value = broadcasting_array * 1.45
broadcasting_value

array([1.45, 2.9 , 5.8 ], dtype=float16)

In [72]:
broadcasting_value.max()

5.8

In [73]:
broadcasting_value.min()

1.45

In [74]:
broadcasting_value.sum()

10.15

In [75]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [76]:
a.sum()

4.8595784

In [77]:
a.sum(axis=0)

array([1.12378257, 1.04875507, 1.01034462, 1.67669614])

In [78]:
a.sum(axis=1)

array([1.51832856, 1.55434556, 1.78690428])

In [79]:
a.max()

0.82485143

In [80]:
a.max(axis=0)

array([0.54627315, 0.82485143, 0.40067661, 0.56917101])

In [81]:
a.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [82]:
a.min()

0.05093587

In [83]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [84]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [85]:
data = np.array([[1,2], [3,4], [5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
data[:,:]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [88]:
data[1:,:]

array([[3, 4],
       [5, 6]])

In [90]:
data[1:,:].max()

6

In [91]:
data[1:,:].min()

3

In [92]:
data[1:,:].sum()

18

In [94]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [95]:
ones_row = np.array([[1, 1]])
ones_row

array([[1, 1]])

In [96]:
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [97]:
np.ones(3)

array([1., 1., 1.])

In [98]:
np.zeros(3)

array([0., 0., 0.])

In [99]:
rng = np.random.default_rng()
rng.random(3)

array([0.8581791 , 0.32215943, 0.34835357])

In [100]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [101]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [102]:
rng.random((2,3))

array([[0.00630306, 0.10477367, 0.06412214],
       [0.49085634, 0.1631794 , 0.33039932]])

In [104]:
rng.integers(5, size=(4,4))

array([[4, 4, 0, 1],
       [3, 2, 1, 2],
       [0, 2, 4, 0],
       [1, 0, 4, 3]], dtype=int64)

In [105]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
a

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [106]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [107]:
np.unique(a, return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64))

In [110]:
np.unique(a, return_counts=True) 

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1], dtype=int64))

In [111]:
np.unique(a, return_inverse=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([0, 0, 1, 2, 3, 4, 5, 6, 1, 2, 0, 3, 7, 8, 9], dtype=int64))

In [112]:
twoDimensionalMatrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
twoDimensionalMatrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [113]:
np.unique(twoDimensionalMatrix, axis = 0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [114]:
np.unique(twoDimensionalMatrix, axis = 1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [115]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [117]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [118]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [120]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [121]:
np.flip(a)

array([20, 19, 18, 14, 11, 13, 12, 17, 16, 15, 14, 13, 12, 11, 11])

In [122]:
matrix2Dimensional = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix2Dimensional

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [123]:
np.flip(matrix2Dimensional)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [126]:
reveresed_column = np.flip(matrix2Dimensional, axis=0)
reveresed_column

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [127]:
reversed_rows = np.flip(matrix2Dimensional, axis=1)
reversed_rows

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])