In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3], 
             [4,5,6]])

In [4]:
a.shape

(2, 3)

In [5]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
a[0]

1

In [8]:
a[0]=10
a

array([10,  2,  3,  4,  5,  6,  7,  8])

In [9]:
a[0:3]

array([10,  2,  3])

In [10]:
a[:4]

array([10,  2,  3,  4])

In [11]:
a[5:]

array([6, 7, 8])

In [12]:
a = np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])
a

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
a[1,2]

6

In [14]:
a[1:, 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [15]:
a.ndim

2

In [16]:
a.shape

(3, 4)

In [17]:
len(a.shape) == a.ndim

True

In [18]:
a.size

12

In [19]:
a.dtype

dtype('int32')

In [20]:
np.zeros(4)

array([0., 0., 0., 0.])

In [21]:
np.zeros((2,3), np.int8)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [22]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
np.ones((4,4,5), np.float16)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float16)

In [28]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.arange(4)

array([0, 1, 2, 3])

In [30]:
np.arange(2,100)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
       70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [31]:
np.arange(2,100,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50,
       53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [32]:
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [33]:
array = np.array([45,12,234,67,89,90,123,54])
np.sort(array)

array([ 12,  45,  54,  67,  89,  90, 123, 234])

In [35]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [39]:
array_example.shape

(3, 2, 4)

In [40]:
array_example.ndim

3

In [41]:
array_example.size

24

In [42]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [44]:
b = a.reshape((2,3))
b

array([[0, 1, 2],
       [3, 4, 5]])

In [46]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [47]:
a = a[np.newaxis,:]
a.shape

(1, 6)

In [48]:
vector = np.array([2,4,6,8,10])
vector.shape

(5,)

In [50]:
row_vector = vector[np.newaxis,:]
row_vector.shape

(1, 5)

In [51]:
column_vector = vector[:, np.newaxis]
column_vector.shape

(5, 1)

In [52]:
vector = np.array([1,3,5,7,9])
vector.shape

(5,)

In [53]:
row_vector = np.expand_dims(vector, axis = 0)
row_vector.shape

(1, 5)

In [54]:
column_vector = np.expand_dims(vector, axis = 1)
column_vector.shape

(5, 1)

In [55]:
data = np.array([1,2,3,4])
data

array([1, 2, 3, 4])

In [56]:
data[0]

1

In [57]:
data[0:3]

array([1, 2, 3])

In [58]:
data[:3]

array([1, 2, 3])

In [59]:
data[2:4]

array([3, 4])

In [61]:
data[3:]

array([4])

In [62]:
a = np.array([[1,2,3,4], [4,5,6,7], [8,9,10,11]])
a

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
a[a>5].reshape((2,3))

array([[ 6,  7,  8],
       [ 9, 10, 11]])